### PR TITLE
dwi2mask: refactor input / output

### PR DESCRIPTION
**Pull request by Lestropie**
- Centralise code for generating a mean *b*=0 image, and allow individual algorithms to request or decline generation of that method, rather than duplicating the code for generating such.

- Have the `execute()` function of each algorithm return the filesystem path of the final generated mask, so that the code responsible for exporting the mask to the user-specified output location can be centralised rather than duplicated in each algorithm.

@RicardoRios46 @wtsyeda : Note that depending on the order in which Pull Requests are used to merge code into the central `dwi2mask` branch, it may be necessary to modify your algorithm code to conform to these structural changes.

### CODE REVIEW

**Comment by RicardoRios46** [comment]
So how the call for the `needs_mean_bzero()` works? 

Do you create some kind of function with the   `if alg.needs_mean_bzero():` on the dwi2mask file?

**Comment by Lestropie** [comment]
Yep: `execute()` within `dwi2mask` just does "`if alg.needs_mean_bzero():`", and writes the mean *b*=0 image to the scratch directory with a known file name ("`bzero.nii`"), only for those algorithms that need it. Just prevents duplicating the code for generating the mean *b*=0 image across multiple algorithm source files.

**Comment by RicardoRios46** [comment]
Oh I see !
There was some documentation about the algorithm and modules library right? I lost the link that you gave me yesterday, or maybe I am just confusing it with another thing  Can you share it again please?

**Comment by Lestropie** [comment]
This isn't something that is built into the `algorithm` module, it's purely changes I made in #7 in order to reduce code duplication. Previously the code for generation of the mean *b*=0 image appeared in about half of the algorithm source files, and the mask export step was almost identical code in every algorithm file; now both of those code blocks appear only once.

**Comment by RicardoRios46** [comment]
Yeah I think I got that part. I just want to read more about the algorithm module hehe

**Comment by Lestropie** [comment]
I don't have documentation on all of the modules; I should ideally have docstrings all over the whole API, but it's one of many things I've not had the time to invest in. So I tend to just stick to the advice of starting with a similar script that already uses the module as intended and modify from there.

**Comment by RicardoRios46** [comment]
Okey! Thank you for the answers. And that's probably the better way to learn coding stuff anyway haha. Good night!

**Comment by Lestropie** [comment]
Cheers for your contribution; about to present our outcomes in the APAC wrap-up session :+1:

**Pull request merged**
